// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtkb9D4ocHSNDD4J1YwZv9rrK7ZOySwbg',
    appId: '1:381743404612:web:8eb0531b9d781571760e11',
    messagingSenderId: '381743404612',
    projectId: 'whatsapp-backend-e6a6c',
    authDomain: 'whatsapp-backend-e6a6c.firebaseapp.com',
    storageBucket: 'whatsapp-backend-e6a6c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvApYBPB2W56_Ou1uMYc1GUb4_O9hiAeg',
    appId: '1:381743404612:android:377c55ad29eee7e3760e11',
    messagingSenderId: '381743404612',
    projectId: 'whatsapp-backend-e6a6c',
    storageBucket: 'whatsapp-backend-e6a6c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-_KwxUOKUnvU8IwovZKtZg9msQy4JMQs',
    appId: '1:381743404612:ios:ce2bffee3518756c760e11',
    messagingSenderId: '381743404612',
    projectId: 'whatsapp-backend-e6a6c',
    storageBucket: 'whatsapp-backend-e6a6c.appspot.com',
    iosClientId: '381743404612-rj24j47lp53mbji6k8pevs6dgvcg7svd.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappUi',
  );
}
